tabela = ("Botafogo", "Palmeiras", "Red Bull Bragantino", "Grêmio", "Atlético-MG", "Flamengo", "Athletico-PR", "Fluminense", "Fortaleza", "São Paulo", "Internacional", "Cuiabá", "Corinthians", "Bahia", "Santos", "Cruzeir", "Goiás", "Vasco", "Coritiba América-MG"	)
print("=" * 100)
print(f"os primeiros colocados são: {tabela[:6]}")
print("=" * 100)
print(f"os 4 ultimos colocados são: {tabela[16:]}")
print("=" * 100)
print(f" os times por orden alfabetica:{sorted(tabela)}")
print("=" * 100)
print(f"A possição do Corinthians é a {tabela.index('Corinthians')}")
print("=" * 100)